#!/usr/bin/env python3

# This script builds the gnome runtime snap using a local SDK snap.

import sys
import os

BASE_CONFIG = 'snap/snapcraft.yaml'
MODIFIED_CONFIG = 'snapcraft.yaml'
SDK_FILE = 'gnome-46-2404-sdk.snap'

if len(sys.argv) > 1:
    SDK_FILE = sys.argv[1]

# If there is a modified snapcraft.yaml, delete it before re-generating it
if os.path.exists(f'./{MODIFIED_CONFIG}'):
    os.remove(f'./{MODIFIED_CONFIG}')

if not os.path.exists(f'./{SDK_FILE}'):
    print(f'There is no valid "{SDK_FILE}" file. Aborting.', file=sys.stderr)
    sys.exit(1)

with open(f'./{BASE_CONFIG}', "r") as config_file:
    config = config_file.readlines()

with open(f'./{MODIFIED_CONFIG}', "w") as config_file:
    config_file.write('# DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED\n')
    config_file.write('# Edit snap/snapcraft.yaml and re-run the local-build.py script\n\n')
    for line in config:
        if line.strip().startswith('stage-snaps:'):
            # remove the stage-snaps in gnome-sdk
            continue
        if line.strip().startswith('LOCAL_SDK_SNAP='):
            pos = line.find('=')
            line = f'{line[:pos]}="{SDK_FILE}"\n'
        config_file.write(line)

os.system('snapcraft clean')
os.system('snapcraft pack -v')
os.remove(f'./{MODIFIED_CONFIG}')
