name: gnome-3-38-2004
version: git
summary: Shared GNOME 3.38 Ubuntu stack
description: |
 This snap includes a GNOME 3.38 stack (the base libraries and desktop 
 integration components) and shares it through the content interface. 
confinement: strict
grade: stable
icon: icon.png
base: core20
compression: lzo

# the recommended mountpoint for that content is /gnome-platform
slots:
    gnome-3-38-2004:
      interface: content
      read:
        - /

parts:
  gnome-sdk:
    plugin: nil
    stage-snaps: [ gnome-3-38-2004-sdk/latest/candidate ]
    stage:
      - lib/*/bindtextdomain.so
      - usr
      
      - -usr/**/*.a
      - -usr/**/*.c
      - -usr/**/*.cpp
      - -usr/**/*.o
      - -usr/**/*.h
      - -usr/**/*.hpp
      - -usr/**/*.pc

      - -usr/bin/g++*
      - -usr/bin/*-linux-gnu-g++*
      - -usr/bin/gcc*
      - -usr/bin/*-linux-gnu-gcc*
      - -usr/bin/python*
      - -usr/bin/vala*
      - -usr/bin/vapi*

      - -usr/include

      - -usr/lib/*vala*

      - -usr/share/perl
      - -usr/share/vala*
      - -usr/share/gir*

  debs:
    after: [ gnome-sdk ]
    plugin: nil
    stage-packages:
      - fcitx-frontend-gtk3
      - fonts-noto-color-emoji
      - gir1.2-ggit-1.0
      - gir1.2-gucharmap-2.90
      - gir1.2-vte-2.91
      - ibus-gtk3
      - libappindicator3-1
      - libindicator3-7
      - libasound2
      - libasyncns0
      - libavahi-client3
      - libavahi-common3
      - libbrotli1
      - libc-bin
      - libcdt5
      - libcgraph6
      - libcolord2
      - libcups2
      - libdatrie1
      - libdbus-glib-1-2
      - libdb5.3
      - libevdev2
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgck-1-0
      - libgcr-base-3-1
      - libgcr-ui-3-1
      - libgl1
      - libgl1-mesa-dri
      - libgoa-1.0-0b
      - libgraphite2-3
      - libgspell-1-2
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libgtk3-nocsd0
      - libgvc6
      - libicu66
      - libinput10
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - libllvm11
      - libmpc3
      - libmpfr6
      - libmtdev1
      - libogg0
      - libpathplan4
      - libpng16-16
      - libpulse0
      - librsvg2-2
      - libsndfile1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libwacom2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwebkit2gtk-4.0-37
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxft2
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxtst6
      - locales-all
      - python3-dbus
      - python3-gi
      - shared-mime-info
      - ubuntu-settings
      - unity-gtk3-module
      - xdg-user-dirs
      - libgtksourceview-3.0-1
      - libmozjs-68-0
      - libsigc++-2.0-0v5
      - libpython3.8
      # VA-API drivers for HW-accelerated video decoding
      - mesa-va-drivers
      - on amd64:
        - i965-va-driver
        - intel-media-va-driver
    stage:
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libLLVM*
    override-build: |
      set -eux
      snapcraftctl build
      cd $SNAPCRAFT_STAGE/usr
      find . -type f,l -exec rm -f $SNAPCRAFT_PART_INSTALL/usr/{} \;
      find . -type f,l -name "*.so*" -exec bash -c "rm -f $SNAPCRAFT_PART_INSTALL/usr/{}*" \;
      cd $SNAPCRAFT_STAGE/usr/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/{} \;
      find . -type f,l -name "*.so*" -exec bash -c "rm -f $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/{}*" \;
      cd $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      find . -type f,l -exec rm -f $SNAPCRAFT_PART_INSTALL/usr/lib/{} \;
      find . -type f,l -name "*.so*" -exec bash -c "rm -f $SNAPCRAFT_PART_INSTALL/usr/lib/{}*" \;

  fonts-config:
      after: [ debs ]
      plugin: nil
      stage-packages: [ fontconfig-config, fonts-arphic-ukai, fonts-arphic-uming, fonts-beng-extra, fonts-dejavu-core, fonts-deva-extra, fonts-droid-fallback, fonts-gubbi, fonts-gujr-extra, fonts-guru-extra, fonts-khmeros-core, fonts-lohit-beng-assamese, fonts-lohit-beng-bengali, fonts-lohit-deva, fonts-lohit-gujr, fonts-lohit-guru, fonts-lohit-knda, fonts-lohit-orya, fonts-lohit-taml, fonts-lohit-taml-classical, fonts-lohit-telu, fonts-noto-cjk, fonts-opensymbol, fonts-orya-extra, fonts-pagul, fonts-smc-anjalioldlipi, fonts-smc-chilanka, fonts-smc-dyuthi, fonts-smc-karumbi, fonts-smc-keraleeyam, fonts-smc-manjari, fonts-smc-meera, fonts-smc-rachana, fonts-smc-raghumalayalamsans, fonts-smc-suruma, fonts-smc-uroob, fonts-telu-extra, fonts-tlwg-garuda, fonts-tlwg-kinnari, fonts-tlwg-laksaman, fonts-tlwg-loma, fonts-tlwg-mono, fonts-tlwg-norasi, fonts-tlwg-typist, fonts-tlwg-typo, fonts-tlwg-umpush, fonts-tlwg-waree, fonts-urw-base35 ]
      stage:
      - etc/fonts
      - usr/share/fontconfig

  caches:
    after: [ fonts-config ]
    plugin: nil
    build-packages:
      - gtk-update-icon-cache
      - libglib2.0-bin
      - shared-mime-info
    override-build: |
      set -eux
      snapcraftctl build
      glib-compile-schemas $SNAPCRAFT_STAGE/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_STAGE/usr/share/mime
      for dir in $SNAPCRAFT_STAGE/usr/share/icons/*; do
        if [ -f "$dir/index.theme" ]; then
          gtk-update-icon-cache --force "$dir"
        fi
      done

  cleanup:
    after: [ caches ]
    plugin: nil
    build-snaps:
      - gtk-common-themes
    override-prime: |
      set -eux

      cd /snap/gtk-common-themes/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/{} \;
      cd $SNAPCRAFT_PRIME

      rm -rf usr/share/doc
      rm -rf usr/share/man

      find . -type d -empty -delete

      # Needed to work around a packaging bug in libmozjs from focal
      ln -sfr usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmozjs-68.so.68.6.0 usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libmozjs-68.so.0
