name: gnome-3-32-1804
version: git
summary: Shared GNOME 3.32 Ubuntu stack
description: |
 This snap includes a GNOME 3.32 stack (the base libraries and desktop 
 integration components) and shares it through the content interface. 
confinement: strict
grade: stable
icon: icon.png
base: core18

# the recommended mountpoint for that content is /gnome-platform
slots:
    gnome-3-32-1804:
      interface: content
      read:
        - /

parts:
  gnome-sdk:
    plugin: nil
    stage-snaps: [ gnome-3-32-1804-sdk/latest/edge ]
    stage:
      - usr
      - -usr/include
      - -usr/**/*.a
      - -usr/**/*.c
      - -usr/**/*.cpp
      - -usr/**/*.o
      - -usr/**/*.gz
      - -usr/**/*.h
      - -usr/**/*.hpp
      - -usr/**/*.pc
      - -usr/bin/g++*
      - -usr/bin/x86_64-linux-gnu-g++*
      - -usr/bin/gcc*
      - -usr/bin/x86_64-linux-gnu-gcc*
      - -usr/bin/python*
      - -usr/bin/vala*

  debs:
    after: [ gnome-sdk ]
    plugin: nil
    stage-packages:
      - fcitx-frontend-gtk3
      - fonts-noto-color-emoji
      - gir1.2-ggit-1.0
      - gir1.2-gucharmap-2.90
      - gir1.2-vte-2.91
      - ibus-gtk3
      - libasound2
      - libasyncns0
      - libavahi-client3
      - libavahi-common3
      - libbrotli1
      - libc-bin
      - libcdt5
      - libcgraph6
      - libcolord2
      - libcups2
      - libdatrie1
      - libdb5.3
      - libevdev2
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgck-1-0
      - libgcr-base-3-1
      - libgcr-ui-3-1
      - libgl1
      - libgl1-mesa-dri
      - libgoa-1.0-0b
      - libgraphite2-3
      - libgspell-1-1
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libgvc6
      - libicu60
      - libinput10
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - libllvm4.0
      - libmpc3
      - libmpfr6
      - libmtdev1
      - libogg0
      - libpathplan4
      - libpng16-16
      - libpulse0
      - librsvg2-2
      - libsndfile1
      - libtdb1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwacom2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwebkit2gtk-4.0-37
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxft2
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxtst6
      - locales-all
      - python3-dbus
      - python3-gi
      - shared-mime-info
      - ubuntu-settings
      - unity-gtk3-module
      - xdg-user-dirs
    stage:
      - -usr/lib/x86_64-linux-gnu/libLLVM-4.0.so*
    override-build: |
      set -eux
      snapcraftctl build
      cd $SNAPCRAFT_STAGE/usr
      find . -type f,l -exec rm -f $SNAPCRAFT_PART_INSTALL/usr/{} \;
      find . -type f,l -name "*.so*" -exec bash -c "rm -f $SNAPCRAFT_PART_INSTALL/usr/{}.*" \;

  last:
    after: [ debs ]
    plugin: nil
    build-packages:
      - gtk-update-icon-cache
      - libglib2.0-bin
      - shared-mime-info
    override-build: |
      set -eux
      snapcraftctl build
      glib-compile-schemas $SNAPCRAFT_STAGE/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_STAGE/usr/share/mime
      for dir in $SNAPCRAFT_STAGE/usr/share/icons/*; do
        if [ -f "$dir/index.theme" ]; then
          gtk-update-icon-cache --force "$dir"
        fi
      done
