name: 🧪 Test snap can be built on x86_64

on:
  pull_request:
    branches: [ gnome-42-2204-sdk, gnome-42-2204 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: snapcraft-build
        
      - uses: actions/upload-artifact@v3
        with:
          name: gnome-sdk
          path: ${{ steps.snapcraft-build.outputs.snap }}    
          
